# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-and-test:

    executor:
      name: android/android-machine

    steps:
      - checkout

      - run:
          name: Touch local properties
          command: touch local.properties

      - run:
          name: Add Empty Private Api Key
          command: echo "MARVEL_PRIVATE_KEY=privatekey" >> local.properties

      - run:
          name: Add Empty Public Api Key
          command: echo "MARVEL_PUBLIC_KEY=publickey" >> local.properties

      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-28;google_apis;x86

      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease

workflows:
  marvel-compose:
    jobs:
      - build-and-test
